
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Entry entradaTexto;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.SpinButton clave;
	
	private global::Gtk.HButtonBox hbuttonbox1;
	
	private global::Gtk.Entry salidaTexto;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Button procesar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(9));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(9));
		// Container child vbox1.Gtk.Box+BoxChild
		this.entradaTexto = new global::Gtk.Entry ();
		this.entradaTexto.HeightRequest = 40;
		this.entradaTexto.CanFocus = true;
		this.entradaTexto.Name = "entradaTexto";
		this.entradaTexto.Text = global::Mono.Unix.Catalog.GetString ("Ingrese texto");
		this.entradaTexto.IsEditable = true;
		this.entradaTexto.InvisibleChar = '●';
		this.vbox1.Add (this.entradaTexto);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entradaTexto]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		this.hbox2.BorderWidth = ((uint)(3));
		// Container child hbox2.Gtk.Box+BoxChild
		this.clave = new global::Gtk.SpinButton (0, 20, 1);
		this.clave.CanFocus = true;
		this.clave.Name = "clave";
		this.clave.Adjustment.PageIncrement = 10;
		this.clave.ClimbRate = 1;
		this.clave.Numeric = true;
		this.hbox2.Add (this.clave);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.clave]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hbuttonbox1 = new global::Gtk.HButtonBox ();
		this.hbuttonbox1.Name = "hbuttonbox1";
		this.hbox2.Add (this.hbuttonbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbuttonbox1]));
		w3.Position = 1;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.salidaTexto = new global::Gtk.Entry ();
		this.salidaTexto.HeightRequest = 40;
		this.salidaTexto.CanFocus = true;
		this.salidaTexto.Name = "salidaTexto";
		this.salidaTexto.IsEditable = true;
		this.salidaTexto.InvisibleChar = '●';
		this.vbox1.Add (this.salidaTexto);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.salidaTexto]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.procesar = new global::Gtk.Button ();
		this.procesar.WidthRequest = 100;
		this.procesar.HeightRequest = 40;
		this.procesar.CanFocus = true;
		this.procesar.Name = "procesar";
		this.procesar.UseUnderline = true;
		this.procesar.Label = global::Mono.Unix.Catalog.GetString ("Procesar");
		this.hbox1.Add (this.procesar);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.procesar]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w7.Position = 6;
		w7.Expand = false;
		w7.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 617;
		this.DefaultHeight = 498;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.procesar.Clicked += new global::System.EventHandler (this.Procesar);
	}
}
